#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_İşlemleri_Otomasyonu.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Stok_Otomasyonu")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_Stoklar(TBL_Stoklar instance);
    partial void UpdateTBL_Stoklar(TBL_Stoklar instance);
    partial void DeleteTBL_Stoklar(TBL_Stoklar instance);
    partial void InsertTBL_Stok_Grupları(TBL_Stok_Grupları instance);
    partial void UpdateTBL_Stok_Grupları(TBL_Stok_Grupları instance);
    partial void DeleteTBL_Stok_Grupları(TBL_Stok_Grupları instance);
    partial void InsertTBL_CariGruplari(TBL_CariGruplari instance);
    partial void UpdateTBL_CariGruplari(TBL_CariGruplari instance);
    partial void DeleteTBL_CariGruplari(TBL_CariGruplari instance);
    partial void InsertTBL_Cariler(TBL_Cariler instance);
    partial void UpdateTBL_Cariler(TBL_Cariler instance);
    partial void DeleteTBL_Cariler(TBL_Cariler instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::Stok_İşlemleri_Otomasyonu.Properties.Settings.Default.Stok_OtomasyonuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_Stoklar> TBL_Stoklars
		{
			get
			{
				return this.GetTable<TBL_Stoklar>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Stok_Grupları> TBL_Stok_Gruplarıs
		{
			get
			{
				return this.GetTable<TBL_Stok_Grupları>();
			}
		}
		
		public System.Data.Linq.Table<TBL_CariGruplari> TBL_CariGruplaris
		{
			get
			{
				return this.GetTable<TBL_CariGruplari>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Cariler> TBL_Carilers
		{
			get
			{
				return this.GetTable<TBL_Cariler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Stoklar")]
	public partial class TBL_Stoklar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Stok_Barkod;
		
		private string _Stok_Kodu;
		
		private string _Stok_Adi;
		
		private string _Stok_Birim;
		
		private System.Nullable<decimal> _Stok_Alis_Fiyat;
		
		private System.Nullable<decimal> _Stok_Satis_Fiyat;
		
		private System.Nullable<decimal> _Stok_Alis_KDV;
		
		private System.Nullable<decimal> _Stok_Satis_KDV;
		
		private System.Nullable<int> _Stok_Grup_ID;
		
		private System.Data.Linq.Binary _Stok_Resim;
		
		private System.Nullable<int> _Stok_Save_User;
		
		private System.Nullable<System.DateTime> _Stok_Save_Date;
		
		private System.Nullable<int> _Stok_Edit_User;
		
		private System.Nullable<System.DateTime> _Stok_Edit_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnStok_BarkodChanging(string value);
    partial void OnStok_BarkodChanged();
    partial void OnStok_KoduChanging(string value);
    partial void OnStok_KoduChanged();
    partial void OnStok_AdiChanging(string value);
    partial void OnStok_AdiChanged();
    partial void OnStok_BirimChanging(string value);
    partial void OnStok_BirimChanged();
    partial void OnStok_Alis_FiyatChanging(System.Nullable<decimal> value);
    partial void OnStok_Alis_FiyatChanged();
    partial void OnStok_Satis_FiyatChanging(System.Nullable<decimal> value);
    partial void OnStok_Satis_FiyatChanged();
    partial void OnStok_Alis_KDVChanging(System.Nullable<decimal> value);
    partial void OnStok_Alis_KDVChanged();
    partial void OnStok_Satis_KDVChanging(System.Nullable<decimal> value);
    partial void OnStok_Satis_KDVChanged();
    partial void OnStok_Grup_IDChanging(System.Nullable<int> value);
    partial void OnStok_Grup_IDChanged();
    partial void OnStok_ResimChanging(System.Data.Linq.Binary value);
    partial void OnStok_ResimChanged();
    partial void OnStok_Save_UserChanging(System.Nullable<int> value);
    partial void OnStok_Save_UserChanged();
    partial void OnStok_Save_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnStok_Save_DateChanged();
    partial void OnStok_Edit_UserChanging(System.Nullable<int> value);
    partial void OnStok_Edit_UserChanged();
    partial void OnStok_Edit_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnStok_Edit_DateChanged();
    #endregion
		
		public TBL_Stoklar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Barkod", DbType="NVarChar(30)")]
		public string Stok_Barkod
		{
			get
			{
				return this._Stok_Barkod;
			}
			set
			{
				if ((this._Stok_Barkod != value))
				{
					this.OnStok_BarkodChanging(value);
					this.SendPropertyChanging();
					this._Stok_Barkod = value;
					this.SendPropertyChanged("Stok_Barkod");
					this.OnStok_BarkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Kodu", DbType="NVarChar(20)")]
		public string Stok_Kodu
		{
			get
			{
				return this._Stok_Kodu;
			}
			set
			{
				if ((this._Stok_Kodu != value))
				{
					this.OnStok_KoduChanging(value);
					this.SendPropertyChanging();
					this._Stok_Kodu = value;
					this.SendPropertyChanged("Stok_Kodu");
					this.OnStok_KoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Adi", DbType="NVarChar(50)")]
		public string Stok_Adi
		{
			get
			{
				return this._Stok_Adi;
			}
			set
			{
				if ((this._Stok_Adi != value))
				{
					this.OnStok_AdiChanging(value);
					this.SendPropertyChanging();
					this._Stok_Adi = value;
					this.SendPropertyChanged("Stok_Adi");
					this.OnStok_AdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Birim", DbType="NVarChar(15)")]
		public string Stok_Birim
		{
			get
			{
				return this._Stok_Birim;
			}
			set
			{
				if ((this._Stok_Birim != value))
				{
					this.OnStok_BirimChanging(value);
					this.SendPropertyChanging();
					this._Stok_Birim = value;
					this.SendPropertyChanged("Stok_Birim");
					this.OnStok_BirimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Alis_Fiyat", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Stok_Alis_Fiyat
		{
			get
			{
				return this._Stok_Alis_Fiyat;
			}
			set
			{
				if ((this._Stok_Alis_Fiyat != value))
				{
					this.OnStok_Alis_FiyatChanging(value);
					this.SendPropertyChanging();
					this._Stok_Alis_Fiyat = value;
					this.SendPropertyChanged("Stok_Alis_Fiyat");
					this.OnStok_Alis_FiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Satis_Fiyat", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Stok_Satis_Fiyat
		{
			get
			{
				return this._Stok_Satis_Fiyat;
			}
			set
			{
				if ((this._Stok_Satis_Fiyat != value))
				{
					this.OnStok_Satis_FiyatChanging(value);
					this.SendPropertyChanging();
					this._Stok_Satis_Fiyat = value;
					this.SendPropertyChanged("Stok_Satis_Fiyat");
					this.OnStok_Satis_FiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Alis_KDV", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Stok_Alis_KDV
		{
			get
			{
				return this._Stok_Alis_KDV;
			}
			set
			{
				if ((this._Stok_Alis_KDV != value))
				{
					this.OnStok_Alis_KDVChanging(value);
					this.SendPropertyChanging();
					this._Stok_Alis_KDV = value;
					this.SendPropertyChanged("Stok_Alis_KDV");
					this.OnStok_Alis_KDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Satis_KDV", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Stok_Satis_KDV
		{
			get
			{
				return this._Stok_Satis_KDV;
			}
			set
			{
				if ((this._Stok_Satis_KDV != value))
				{
					this.OnStok_Satis_KDVChanging(value);
					this.SendPropertyChanging();
					this._Stok_Satis_KDV = value;
					this.SendPropertyChanged("Stok_Satis_KDV");
					this.OnStok_Satis_KDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Grup_ID", DbType="Int")]
		public System.Nullable<int> Stok_Grup_ID
		{
			get
			{
				return this._Stok_Grup_ID;
			}
			set
			{
				if ((this._Stok_Grup_ID != value))
				{
					this.OnStok_Grup_IDChanging(value);
					this.SendPropertyChanging();
					this._Stok_Grup_ID = value;
					this.SendPropertyChanged("Stok_Grup_ID");
					this.OnStok_Grup_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Resim", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Stok_Resim
		{
			get
			{
				return this._Stok_Resim;
			}
			set
			{
				if ((this._Stok_Resim != value))
				{
					this.OnStok_ResimChanging(value);
					this.SendPropertyChanging();
					this._Stok_Resim = value;
					this.SendPropertyChanged("Stok_Resim");
					this.OnStok_ResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Save_User", DbType="Int")]
		public System.Nullable<int> Stok_Save_User
		{
			get
			{
				return this._Stok_Save_User;
			}
			set
			{
				if ((this._Stok_Save_User != value))
				{
					this.OnStok_Save_UserChanging(value);
					this.SendPropertyChanging();
					this._Stok_Save_User = value;
					this.SendPropertyChanged("Stok_Save_User");
					this.OnStok_Save_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Save_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Stok_Save_Date
		{
			get
			{
				return this._Stok_Save_Date;
			}
			set
			{
				if ((this._Stok_Save_Date != value))
				{
					this.OnStok_Save_DateChanging(value);
					this.SendPropertyChanging();
					this._Stok_Save_Date = value;
					this.SendPropertyChanged("Stok_Save_Date");
					this.OnStok_Save_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Edit_User", DbType="Int")]
		public System.Nullable<int> Stok_Edit_User
		{
			get
			{
				return this._Stok_Edit_User;
			}
			set
			{
				if ((this._Stok_Edit_User != value))
				{
					this.OnStok_Edit_UserChanging(value);
					this.SendPropertyChanging();
					this._Stok_Edit_User = value;
					this.SendPropertyChanged("Stok_Edit_User");
					this.OnStok_Edit_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok_Edit_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Stok_Edit_Date
		{
			get
			{
				return this._Stok_Edit_Date;
			}
			set
			{
				if ((this._Stok_Edit_Date != value))
				{
					this.OnStok_Edit_DateChanging(value);
					this.SendPropertyChanging();
					this._Stok_Edit_Date = value;
					this.SendPropertyChanged("Stok_Edit_Date");
					this.OnStok_Edit_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Stok_Grupları")]
	public partial class TBL_Stok_Grupları : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Grup_Adi;
		
		private string _Grup_Kodu;
		
		private System.Nullable<int> _Grup_Save_User;
		
		private System.Nullable<System.DateTime> _Grup_Save_Date;
		
		private System.Nullable<int> _Grup_Edit_User;
		
		private System.Nullable<System.DateTime> _Grup_Edit_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGrup_AdiChanging(string value);
    partial void OnGrup_AdiChanged();
    partial void OnGrup_KoduChanging(string value);
    partial void OnGrup_KoduChanged();
    partial void OnGrup_Save_UserChanging(System.Nullable<int> value);
    partial void OnGrup_Save_UserChanged();
    partial void OnGrup_Save_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnGrup_Save_DateChanged();
    partial void OnGrup_Edit_UserChanging(System.Nullable<int> value);
    partial void OnGrup_Edit_UserChanged();
    partial void OnGrup_Edit_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnGrup_Edit_DateChanged();
    #endregion
		
		public TBL_Stok_Grupları()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grup_Adi", DbType="NVarChar(30)")]
		public string Grup_Adi
		{
			get
			{
				return this._Grup_Adi;
			}
			set
			{
				if ((this._Grup_Adi != value))
				{
					this.OnGrup_AdiChanging(value);
					this.SendPropertyChanging();
					this._Grup_Adi = value;
					this.SendPropertyChanged("Grup_Adi");
					this.OnGrup_AdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grup_Kodu", DbType="NVarChar(30)")]
		public string Grup_Kodu
		{
			get
			{
				return this._Grup_Kodu;
			}
			set
			{
				if ((this._Grup_Kodu != value))
				{
					this.OnGrup_KoduChanging(value);
					this.SendPropertyChanging();
					this._Grup_Kodu = value;
					this.SendPropertyChanged("Grup_Kodu");
					this.OnGrup_KoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grup_Save_User", DbType="Int")]
		public System.Nullable<int> Grup_Save_User
		{
			get
			{
				return this._Grup_Save_User;
			}
			set
			{
				if ((this._Grup_Save_User != value))
				{
					this.OnGrup_Save_UserChanging(value);
					this.SendPropertyChanging();
					this._Grup_Save_User = value;
					this.SendPropertyChanged("Grup_Save_User");
					this.OnGrup_Save_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grup_Save_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Grup_Save_Date
		{
			get
			{
				return this._Grup_Save_Date;
			}
			set
			{
				if ((this._Grup_Save_Date != value))
				{
					this.OnGrup_Save_DateChanging(value);
					this.SendPropertyChanging();
					this._Grup_Save_Date = value;
					this.SendPropertyChanged("Grup_Save_Date");
					this.OnGrup_Save_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grup_Edit_User", DbType="Int")]
		public System.Nullable<int> Grup_Edit_User
		{
			get
			{
				return this._Grup_Edit_User;
			}
			set
			{
				if ((this._Grup_Edit_User != value))
				{
					this.OnGrup_Edit_UserChanging(value);
					this.SendPropertyChanging();
					this._Grup_Edit_User = value;
					this.SendPropertyChanged("Grup_Edit_User");
					this.OnGrup_Edit_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grup_Edit_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Grup_Edit_Date
		{
			get
			{
				return this._Grup_Edit_Date;
			}
			set
			{
				if ((this._Grup_Edit_Date != value))
				{
					this.OnGrup_Edit_DateChanging(value);
					this.SendPropertyChanging();
					this._Grup_Edit_Date = value;
					this.SendPropertyChanged("Grup_Edit_Date");
					this.OnGrup_Edit_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CariGruplari")]
	public partial class TBL_CariGruplari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GRUPADI;
		
		private string _GRUPKODU;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDİTDATE;
		
		private System.Nullable<int> _EDİTUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGRUPADIChanging(string value);
    partial void OnGRUPADIChanged();
    partial void OnGRUPKODUChanging(string value);
    partial void OnGRUPKODUChanged();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDİTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDİTDATEChanged();
    partial void OnEDİTUSERChanging(System.Nullable<int> value);
    partial void OnEDİTUSERChanged();
    #endregion
		
		public TBL_CariGruplari()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPADI", DbType="NVarChar(30)")]
		public string GRUPADI
		{
			get
			{
				return this._GRUPADI;
			}
			set
			{
				if ((this._GRUPADI != value))
				{
					this.OnGRUPADIChanging(value);
					this.SendPropertyChanging();
					this._GRUPADI = value;
					this.SendPropertyChanged("GRUPADI");
					this.OnGRUPADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPKODU", DbType="NVarChar(30)")]
		public string GRUPKODU
		{
			get
			{
				return this._GRUPKODU;
			}
			set
			{
				if ((this._GRUPKODU != value))
				{
					this.OnGRUPKODUChanging(value);
					this.SendPropertyChanging();
					this._GRUPKODU = value;
					this.SendPropertyChanged("GRUPKODU");
					this.OnGRUPKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDİTDATE
		{
			get
			{
				return this._EDİTDATE;
			}
			set
			{
				if ((this._EDİTDATE != value))
				{
					this.OnEDİTDATEChanging(value);
					this.SendPropertyChanging();
					this._EDİTDATE = value;
					this.SendPropertyChanged("EDİTDATE");
					this.OnEDİTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDİTUSER", DbType="Int")]
		public System.Nullable<int> EDİTUSER
		{
			get
			{
				return this._EDİTUSER;
			}
			set
			{
				if ((this._EDİTUSER != value))
				{
					this.OnEDİTUSERChanging(value);
					this.SendPropertyChanging();
					this._EDİTUSER = value;
					this.SendPropertyChanged("EDİTUSER");
					this.OnEDİTUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Cariler")]
	public partial class TBL_Cariler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CARIKODU;
		
		private string @__CARIADI;
		
		private string _VERGIDAIRESI;
		
		private string _VERGINO;
		
		private System.Nullable<int> _GRUPID;
		
		private string _ULKE;
		
		private string _SEHIR;
		
		private string _ILCE;
		
		private string _ADRES;
		
		private string _TELEFON1;
		
		private string _TELEFON2;
		
		private string _FAX1;
		
		private string _FAX2;
		
		private string _WEBADRES;
		
		private string _MAILBILGI;
		
		private string _YETKILI1;
		
		private string _YETKILI2;
		
		private string _YETKILIMAIL1;
		
		private string _YETKILIMAIL2;
		
		private System.Nullable<System.DateTime> _SAVEDATE;
		
		private System.Nullable<int> _SAVEUSER;
		
		private System.Nullable<System.DateTime> _EDITDATE;
		
		private System.Nullable<int> _EDITUSER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCARIKODUChanging(string value);
    partial void OnCARIKODUChanged();
    partial void OnCARIADIChanging(string value);
    partial void OnCARIADIChanged();
    partial void OnVERGIDAIRESIChanging(string value);
    partial void OnVERGIDAIRESIChanged();
    partial void OnVERGINOChanging(string value);
    partial void OnVERGINOChanged();
    partial void OnGRUPIDChanging(System.Nullable<int> value);
    partial void OnGRUPIDChanged();
    partial void OnULKEChanging(string value);
    partial void OnULKEChanged();
    partial void OnSEHIRChanging(string value);
    partial void OnSEHIRChanged();
    partial void OnILCEChanging(string value);
    partial void OnILCEChanged();
    partial void OnADRESChanging(string value);
    partial void OnADRESChanged();
    partial void OnTELEFON1Changing(string value);
    partial void OnTELEFON1Changed();
    partial void OnTELEFON2Changing(string value);
    partial void OnTELEFON2Changed();
    partial void OnFAX1Changing(string value);
    partial void OnFAX1Changed();
    partial void OnFAX2Changing(string value);
    partial void OnFAX2Changed();
    partial void OnWEBADRESChanging(string value);
    partial void OnWEBADRESChanged();
    partial void OnMAILBILGIChanging(string value);
    partial void OnMAILBILGIChanged();
    partial void OnYETKILI1Changing(string value);
    partial void OnYETKILI1Changed();
    partial void OnYETKILI2Changing(string value);
    partial void OnYETKILI2Changed();
    partial void OnYETKILIMAIL1Changing(string value);
    partial void OnYETKILIMAIL1Changed();
    partial void OnYETKILIMAIL2Changing(string value);
    partial void OnYETKILIMAIL2Changed();
    partial void OnSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSAVEDATEChanged();
    partial void OnSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSAVEUSERChanged();
    partial void OnEDITDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEDITDATEChanged();
    partial void OnEDITUSERChanging(System.Nullable<int> value);
    partial void OnEDITUSERChanged();
    #endregion
		
		public TBL_Cariler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARIKODU", DbType="NVarChar(30)")]
		public string CARIKODU
		{
			get
			{
				return this._CARIKODU;
			}
			set
			{
				if ((this._CARIKODU != value))
				{
					this.OnCARIKODUChanging(value);
					this.SendPropertyChanging();
					this._CARIKODU = value;
					this.SendPropertyChanged("CARIKODU");
					this.OnCARIKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="__CARIADI", DbType="NVarChar(30)")]
		public string CARIADI
		{
			get
			{
				return this.@__CARIADI;
			}
			set
			{
				if ((this.@__CARIADI != value))
				{
					this.OnCARIADIChanging(value);
					this.SendPropertyChanging();
					this.@__CARIADI = value;
					this.SendPropertyChanged("CARIADI");
					this.OnCARIADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERGIDAIRESI", DbType="NVarChar(50)")]
		public string VERGIDAIRESI
		{
			get
			{
				return this._VERGIDAIRESI;
			}
			set
			{
				if ((this._VERGIDAIRESI != value))
				{
					this.OnVERGIDAIRESIChanging(value);
					this.SendPropertyChanging();
					this._VERGIDAIRESI = value;
					this.SendPropertyChanged("VERGIDAIRESI");
					this.OnVERGIDAIRESIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERGINO", DbType="NVarChar(20)")]
		public string VERGINO
		{
			get
			{
				return this._VERGINO;
			}
			set
			{
				if ((this._VERGINO != value))
				{
					this.OnVERGINOChanging(value);
					this.SendPropertyChanging();
					this._VERGINO = value;
					this.SendPropertyChanged("VERGINO");
					this.OnVERGINOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPID", DbType="Int")]
		public System.Nullable<int> GRUPID
		{
			get
			{
				return this._GRUPID;
			}
			set
			{
				if ((this._GRUPID != value))
				{
					this.OnGRUPIDChanging(value);
					this.SendPropertyChanging();
					this._GRUPID = value;
					this.SendPropertyChanged("GRUPID");
					this.OnGRUPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ULKE", DbType="NVarChar(30)")]
		public string ULKE
		{
			get
			{
				return this._ULKE;
			}
			set
			{
				if ((this._ULKE != value))
				{
					this.OnULKEChanging(value);
					this.SendPropertyChanging();
					this._ULKE = value;
					this.SendPropertyChanged("ULKE");
					this.OnULKEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEHIR", DbType="NVarChar(30)")]
		public string SEHIR
		{
			get
			{
				return this._SEHIR;
			}
			set
			{
				if ((this._SEHIR != value))
				{
					this.OnSEHIRChanging(value);
					this.SendPropertyChanging();
					this._SEHIR = value;
					this.SendPropertyChanged("SEHIR");
					this.OnSEHIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ILCE", DbType="NVarChar(30)")]
		public string ILCE
		{
			get
			{
				return this._ILCE;
			}
			set
			{
				if ((this._ILCE != value))
				{
					this.OnILCEChanging(value);
					this.SendPropertyChanging();
					this._ILCE = value;
					this.SendPropertyChanged("ILCE");
					this.OnILCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRES", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ADRES
		{
			get
			{
				return this._ADRES;
			}
			set
			{
				if ((this._ADRES != value))
				{
					this.OnADRESChanging(value);
					this.SendPropertyChanging();
					this._ADRES = value;
					this.SendPropertyChanged("ADRES");
					this.OnADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON1", DbType="NVarChar(16)")]
		public string TELEFON1
		{
			get
			{
				return this._TELEFON1;
			}
			set
			{
				if ((this._TELEFON1 != value))
				{
					this.OnTELEFON1Changing(value);
					this.SendPropertyChanging();
					this._TELEFON1 = value;
					this.SendPropertyChanged("TELEFON1");
					this.OnTELEFON1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON2", DbType="NVarChar(16)")]
		public string TELEFON2
		{
			get
			{
				return this._TELEFON2;
			}
			set
			{
				if ((this._TELEFON2 != value))
				{
					this.OnTELEFON2Changing(value);
					this.SendPropertyChanging();
					this._TELEFON2 = value;
					this.SendPropertyChanged("TELEFON2");
					this.OnTELEFON2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX1", DbType="NVarChar(16)")]
		public string FAX1
		{
			get
			{
				return this._FAX1;
			}
			set
			{
				if ((this._FAX1 != value))
				{
					this.OnFAX1Changing(value);
					this.SendPropertyChanging();
					this._FAX1 = value;
					this.SendPropertyChanged("FAX1");
					this.OnFAX1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX2", DbType="NVarChar(16)")]
		public string FAX2
		{
			get
			{
				return this._FAX2;
			}
			set
			{
				if ((this._FAX2 != value))
				{
					this.OnFAX2Changing(value);
					this.SendPropertyChanging();
					this._FAX2 = value;
					this.SendPropertyChanged("FAX2");
					this.OnFAX2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEBADRES", DbType="NVarChar(150)")]
		public string WEBADRES
		{
			get
			{
				return this._WEBADRES;
			}
			set
			{
				if ((this._WEBADRES != value))
				{
					this.OnWEBADRESChanging(value);
					this.SendPropertyChanging();
					this._WEBADRES = value;
					this.SendPropertyChanged("WEBADRES");
					this.OnWEBADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAILBILGI", DbType="NVarChar(300)")]
		public string MAILBILGI
		{
			get
			{
				return this._MAILBILGI;
			}
			set
			{
				if ((this._MAILBILGI != value))
				{
					this.OnMAILBILGIChanging(value);
					this.SendPropertyChanging();
					this._MAILBILGI = value;
					this.SendPropertyChanged("MAILBILGI");
					this.OnMAILBILGIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILI1", DbType="NVarChar(50)")]
		public string YETKILI1
		{
			get
			{
				return this._YETKILI1;
			}
			set
			{
				if ((this._YETKILI1 != value))
				{
					this.OnYETKILI1Changing(value);
					this.SendPropertyChanging();
					this._YETKILI1 = value;
					this.SendPropertyChanged("YETKILI1");
					this.OnYETKILI1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILI2", DbType="NVarChar(50)")]
		public string YETKILI2
		{
			get
			{
				return this._YETKILI2;
			}
			set
			{
				if ((this._YETKILI2 != value))
				{
					this.OnYETKILI2Changing(value);
					this.SendPropertyChanging();
					this._YETKILI2 = value;
					this.SendPropertyChanged("YETKILI2");
					this.OnYETKILI2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILIMAIL1", DbType="NVarChar(250)")]
		public string YETKILIMAIL1
		{
			get
			{
				return this._YETKILIMAIL1;
			}
			set
			{
				if ((this._YETKILIMAIL1 != value))
				{
					this.OnYETKILIMAIL1Changing(value);
					this.SendPropertyChanging();
					this._YETKILIMAIL1 = value;
					this.SendPropertyChanged("YETKILIMAIL1");
					this.OnYETKILIMAIL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILIMAIL2", DbType="NVarChar(250)")]
		public string YETKILIMAIL2
		{
			get
			{
				return this._YETKILIMAIL2;
			}
			set
			{
				if ((this._YETKILIMAIL2 != value))
				{
					this.OnYETKILIMAIL2Changing(value);
					this.SendPropertyChanging();
					this._YETKILIMAIL2 = value;
					this.SendPropertyChanged("YETKILIMAIL2");
					this.OnYETKILIMAIL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SAVEDATE
		{
			get
			{
				return this._SAVEDATE;
			}
			set
			{
				if ((this._SAVEDATE != value))
				{
					this.OnSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._SAVEDATE = value;
					this.SendPropertyChanged("SAVEDATE");
					this.OnSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAVEUSER", DbType="Int")]
		public System.Nullable<int> SAVEUSER
		{
			get
			{
				return this._SAVEUSER;
			}
			set
			{
				if ((this._SAVEUSER != value))
				{
					this.OnSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._SAVEUSER = value;
					this.SendPropertyChanged("SAVEUSER");
					this.OnSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDITDATE
		{
			get
			{
				return this._EDITDATE;
			}
			set
			{
				if ((this._EDITDATE != value))
				{
					this.OnEDITDATEChanging(value);
					this.SendPropertyChanging();
					this._EDITDATE = value;
					this.SendPropertyChanged("EDITDATE");
					this.OnEDITDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDITUSER", DbType="Int")]
		public System.Nullable<int> EDITUSER
		{
			get
			{
				return this._EDITUSER;
			}
			set
			{
				if ((this._EDITUSER != value))
				{
					this.OnEDITUSERChanging(value);
					this.SendPropertyChanging();
					this._EDITUSER = value;
					this.SendPropertyChanged("EDITUSER");
					this.OnEDITUSERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
